on: [push]

jobs:
  test_cov_job:
    runs-on: ubuntu-latest
    name: Test cov job
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test coverage action step
        uses: ./.github/actions/test-cov
